### PR TITLE
Cgsn ctd

### PR DESCRIPTION
**Pull request by reedan88**
Adding the CGSN vehicle CTD gross range parameters and values, as well as a directory and gross range table for AUVs. Also deleted the ID column in the glider gross range table.

### CODE REVIEW

**Review by mvardaro — APPROVED** [review]
Everything looks okay to me. Is there any useful user min/max for the AUV, or should it be set the same for suspect and fail? I'm not sure how the code works - if it's just pass/fail, should we leave user range blank?

**Comment by reedan88** [comment]
@mvardaro I'm not sure I follow the question. Do you mean is it useful to have a user min/max for the AUV? For the user min/max values I took it from the values for the entire array (e.g. Pioneer, Irminger, etc.) from the top and bottom instruments. I think its probably useful because they are tighter ranges than the fail min/max values.

**Comment by mvardaro** [comment]
My question was regarding pressure - we discussed on the QARTOD call. We will wait and see during dev01 testing whether user and sensor min/max being identical causes any issues.

**Comment by reedan88** [comment]
@mvardaro @wruef @cwingard There has been a change since Mike looked at it. I found a bug in my code for the CTDPF instruments where I had multiple entries in the gross range table. I've removed the duplicate entries for CGSN CTDPFs, but it should get a re-review.

**Review by cwingard — APPROVED** [review]

**Review by mvardaro — APPROVED** [review]
Looks good.

**Pull request merged**
