### PR TITLE
Gross Range and Climatology Tables for CGSN PHSENs

### PR DESCRIPTION
**Pull request by reedan88**
These are the gross range table and climatology tables and parameters for CGSN PHSEN instruments.

### CODE REVIEW

**Comment by reedan88** [comment]
Tagging @cwingard @mvardaro @wruef for review. This branch was updated from oceanobservatories/master after merging RCA's and CGSN's last pull requests, so there is (hopefully) no conflicts.

**Comment by reedan88** [comment]
Reupping tag for @cwingard @mvardaro @wruef to review the PHSEN tables from CGSN to get this merged. Thanks!

**Comment by mvardaro** [comment]
The gross range tables look okay to me. It looks like some are using the fail span from the manual of 7.0-9.0 and others are using the software fail span of 6.9-9.0. But as long as it's documented that's fine. I'll let Chris and Wendi weigh in on any climatology issues.

**Comment by reedan88** [comment]
I think that is from your last push, which was the starting point for my tables.

**Comment by cwingard** [comment]
This looks fine to me. Go ahead and merge. We can revisit the phsen fail range and make a global search and replace at a future date to make sure we are all consistent.

**Comment by reedan88** [comment]
@cwingard @mvardaro Can one of you merge? I do not have permission to merge.

**Pull request merged**
