### PR TITLE
Cgsn pco2w

### PR DESCRIPTION
**Pull request by reedan88**
These are the CGSN gross range and climatology parameter and value tables for the PCO2W.

### CODE REVIEW

**Review by cwingard — COMMENTED** [review]
In rows 9 and 10 of pco2w_qartod_gross_range_test_values.csv, you use a fail span of 2 to 1000. Everywhere else, you use 200 to 1000. Are those rows correct? If so, I'll approve. If not, once you update them, I'll approve. Otherwise looks good.

**Review by mvardaro — COMMENTED** [review]
Sorry for the slow response. Everything aside from the "2, 1000" issue Chris found looks good.

**Comment by reedan88** [comment]
Okay, fixed the "2, 1000" issue. @cwingard and @mvardaro can you give it your approval and we can merge this branch? Thanks!

**Review by mvardaro — APPROVED** [review]
LGTM

**Pull request merged**
